name: Feature Request
description: Suggest an idea or enhancement for StreamGuard
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve StreamGuard.
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
      placeholder: "I want to be able to ..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: What would you like to see implemented?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or workarounds?
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add screenshots, logs, or other context
    validations:
      required: false
